[build]
    command = "npm run build"
    functions = "dist"      # where the compiled JS ends up

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api/:splat"
    status = 200

[functions]
    node_bundler = "esbuild"

[functions."*"]            # matches api.js
    timeout = 30