[build]
    command = "npm run build"
    functions = "dist"      # where the compiled JS ends up

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api/:splat"
    status = 200

[functions]
    timeout = 26   # seconds (max allowed without contacting support)